### ISSUE TITLE
StopIteration exception on "a in b"

### ISSUE THREAD

**Issue by demalexx** [AlexandreDecan/portion#28]
Very easy to reproduce:
```python
a = portion.closed(date(2020, 2, 1), date(2020, 2, 28)) | portion.closed(date(2020, 3, 1), date(2020, 3, 31))
b = portion.closed(date(2020, 4, 1), date(2020, 4, 30))
print(b in a)
```
With numbers it's the same:
```python
a = portion.closed(1, 2) | portion.closed(3, 4)
b = portion.closed(5, 6)
print(b in a)
```
Exception:
```
File "venv/lib/python3.8/site-packages/portion/interval.py", line 478, in __contains__
    current = next(selfiter)
StopIteration
```
Is it not supposed to work this way? Or is it a bug?

Thanks!

**Comment by AlexandreDecan** [comment]
Hello,

Thanks for having reported this issue! I'll have a look at it asap. It looks like a bug. I'll confirm and fix it soon.

**Comment by AlexandreDecan** [comment]
I confirm it is a bug. I thought a `StopIteration` raised within the body of a while-loop terminates that loop, but it turns out it's not the case. As a result, when `selfiter` is exhausted, `next` raises a `StopIteration` that's converted by Python to a `RuntimeError`, hence the issue you got. 

I'll release a fix in a few minutes.

**Comment by demalexx** [comment]
Wow, super-fast reaction! Thanks! :)

**Comment by AlexandreDecan** [comment]
Release 2.0.2 is now on PyPI :)

Thanks again for the issue!
