### ISSUE TITLE
question: most performant way to fill up an IntervalDict with 600k intervals?

### ISSUE THREAD

**Issue by spock** [AlexandreDecan/portion#49]
I am trying to import roughly 600k intervals from a text file like this, with start/end/value columns, where values are relatively repetitive, and start-end pairs together form a single long contiguous interval (no gaps):
```
0       119     0
119     120     1
120     130     4
130     133     0
...
```
Right now I am iterating over lines of the file, doing `intervals[P.closedopen(int(start), int(end))] = int(value)` on each parsed line.  
This process becomes progressively slower and slower, dropping to just 20 lines/second after ~6500 lines.  
Upon closer examination, IntervalDict seems to simplify intervals upon each addition in such a way that same-value disjoint intervals are grouped together:

```
IntervalDict.domain of {[119,120) | [375,450) | [671,672) | [705,706) | [870,872) | 
[2271,2276) | [2351,2363) | [2385,2400) | [2477,2503) | [2541,2548) | [2578,2582) | 
[2786,2788) | [3698,3702) | [3706,3756) | [3831,3850) | [3851,3857): 1, [120,130) | 
[292,295) | [586,587) | [880,889) | [1268,1278) | [1306,1321) | [1327,1328) | 
[1381,1396) | [1925,1932) | [2007,2008) | [2018,2023) | [2106,2117) | [2135,2136) |
[2138,2153) | [2196,2213) | [2762,2778) | [2793,2795) | [2891,2898) | [2988,2992) | 
[3114,3122) | [3688,3695) | [3894,3907) | [3925,3932): 4,
```

I believe this is the reason for a progressive slowdown.

My actual questions are:
- is there a more efficient way to populate IntervalDict? for example, by populating a dict first, and then "converting" into IntervalDict?
- is it possible to disable the merging functionality while adding intervals, and then call it once at the end?

**Comment by AlexandreDecan** [comment]
Hello, 

This is a very interesting case. I wrote IntervalDict primarily for convenience, not for performance and, to be honest, I am already surprised that it is possible to inject 6500 lines so "easily". But indeed, we are far from the 600k that is needed ;-) 

The slowdown is most likely due to the fact that each time an interval is added to the dict, it is compared to the existing intervals (there is one for each stored value). If the number of distinct values is large among the 600k lines, the performance will be poor very quickly.  

There is nothing "internally" in `portion` that will allow to bypass interval merging, or to speed up IntervalDict, unfortunately. I think the best solution is probably to "pre-process" the intervals before injecting them into the dict. A "simple" solution would be to use a classical dict, in which each value is associated with a list of intervals.  For your example, that means: 
`{ 0: [P.closedopen(0, 119), P.closedopen(130, 133), ....], 1: [P.closedopen(119, 120), .....}`

As soon as the file is completely read, we can then inject these intervals into an IntervalDict (but first we will group these atomic intervals together). Let's assume `d` is the above dict, and `id` an IntervalDict instance, then:
```python
for value, intervals in d.items():
  interval = P.Interval(*intervals)
  d[interval] = value
```

I think (hope ^^) that should help quite well. 
Please, keep me informed! :-)

**Comment by spock** [comment]
Thanks, I had similar thoughts over night, but it is good to have a confirmation (and sample code) from you. I will give this a try!

**Comment by spock** [comment]
I left the script running overnight, after almost 10.5 hours we are at 98+k lines :) But the speed is now down to 1.2 lines/sec :)

**Comment by AlexandreDecan** [comment]
I'm afraid it's only going to get worse. The more values the IntervalDict contains (and the wider the disjunctions are), the worse the performance will be. 

But that's interesting. I was wondering to what extent the IntervalDict can scale, knowing that most of the internal operations are not optimized, and now I know it does not scale well ;-)

**Comment by spock** [comment]
This new approach promises to finish in under 4 hours.  
I have roughly 2800 distinct values, and these now seem to be added at a fairly stable pace of 4 seconds per value, but it actually keeps growing as I'm watching... Now 5 seconds per value, estimated finish time still ~4 hours.

As the next step, I'll have to issue several million queries to the IntervalDict, but I hope that will go much faster; and if not, I can share the dict across multiple processes and thus speedup the lookups.

I'll let you know when this finishes :)

**Comment by spock** [comment]
Ok, it is back to 4 seconds per value - I guess it simply fluctuates, but doesn't grow.

**Comment by AlexandreDecan** [comment]
I guess that you measure time for the whole loop? If so, that includes the time requires to create the disjunction based on (I guess) a lot of (atomic) intervals. These intervals (when passed to P.Interval.__init__) are sorted first (O(n log n)) and then we try to merge consecutive intervals (that's an additional O(n)). This is not negligible given how many intervals you have but this should take a relatively constant time, so it shoudn't slow down the loop as time passes. 

Internally, for IntervalDict, each distinct value is stored with its corresponding (disjunction of) interval(s). Each time a new value is added, the IntervalDict has to look at all existing intervals to see whether they intersect the new one or not, and to update this structure accordingly. Intersection is quite efficient (it has a O(min(n,m)) complexity, where n and m is the number of atomic intervals in both disjunctions), but since it has to do this for all distinct values, I expect the time to grow linearly in the size of the intervaldict. However, this should be "negligible" compared to the above O(n log n).


And to be honest, I don't think you'll be able to issue several million queries in a reasonable time :( However, if those queries are essentially point queries (i.e. a single value, not an interval), then I already have ideas on how to speed-up this :-)

**Comment by spock** [comment]
I measure the time with `for value, intervals in tqdm(values.items()):` - so yes, this includes both interval merging and adding to the IntervalDict. I did not check how many intervals I have for the values, will add the code for that for the next test run. There should be around 4 million points in those 600k intervals.  

Thanks a lot for the detailed explanation!  

This is a kind of a trial run for me (so if it does finish in 4 hours - that's ok), but I guess for regular use my case might be better catered for with simple numpy arrays...  
I am attracted to `portion`, though, because of easier/cleaner wrapper script that I need (already handling lots of what I'd need to code around numpy arrays), and because of that same interval merging feature, which I'd need to implement myself otherwise :slightly_smiling_face: (I will need it to output the results in a format similar to input).

Yes, querying will be for single values - I need to compare interval values from two IntervalDicts, and change the value in one of them, depending on which is larger/smaller....  
I guess I'll hit the same issue when updating, because if I change the value for just a single point, IntervalDict will need to internally re-arrange intervals and values.  
I could avoid in-place edits and just collect both (modified) results in simple dicts again, and then re-create the IntervalDicts?  
After modifying values, I will have fewer distinct values, but will probably still be in the hours range.  

26% done in 1 hour :)

**Comment by AlexandreDecan** [comment]
Point queries are fast compared to "interval-based" queries. I've just ran a small, informal benchmark on an `IntervalDict` containing 1K intervals for 5 distinct values, and a point query ran on average 30 times faster than an interval-based query. 

I also implemented the changes I had in mind to speed-up these interval-based queries. Currently, when a query is made, we look for an intersection between the key (i.e. the interval) and any stored interval (remember that there is only one single interval for each distinct value). Even if the key is found (in one or more intervals), the process loops on all stored intervals. I made a small change that, at each step, adapt the key so it corresponds to "what it remains to find" (e.g. if we look for [0, 5] and already found a value for [2, 3], then the remaining key is [0,2)|(3,5]). 

I tested this change, and it effectively speed-up the process a little bit for queries (around 20% faster) on average, but it slows down the worst cases by around 50%. That's not unexpected, since it requires to compute the "remaining key" each time part of it is found in an interval. While such computation is not very costly, it still requires several comparisons between bounds, and the creation of new objects, which is definitely not something Python likes :-)

I implemented this change for the "set" and "del" methods as well, hoping that the former would benefit from a speed-up, but I got the opposite: it slowed down the whole process for more than 50%!

I'll continue to see what I can do to speed-up these operations, but I'm afraid you should not expect much :( The `IntervalDict` is definitely not something to look at for performance for now, but the good news is I've a master student who's supposedly working on a brand new implementation of it based on interval trees (but it won't be available, at best, before mid-2021).

**Comment by spock** [comment]
I did consider `bx-python` (lightning-fast and worked with it before), but the interface of `portion` is much more pleasant to work with. And I didn't remember if `bx-python` has support for any kind of values associated with intervals...  

Import finished in 3:45 :slightly_smiling_face: 

I still need to write the filtering part, so will likely be quiet until next week.

Thank you for help so far!

**Comment by AlexandreDecan** [comment]
You're welcome ;)

I close the issue since you found a solution to import these 600k intervals in a "reasonable" time ;-)
Feel free to open a new one for the "query part", since I expect we'll have to find some tricks to speed-up this part as well :)
