### ISSUE TITLE
Invalid strings don't cause any sort of error

### ISSUE THREAD

**Issue by Qix-** [AlexandreDecan/portion#57]
Hi there - firstly, thank you for saving me days of work with this library <3 Hugely appreciated, and it's very well done.

In the following, no error is produced:

```python
import portion as P

ival = P.from_string('[10, 20] | 25', int)
print(ival) #-> "[10,20]"
```

Would it be possible to produce an error if there is unexpected input? Or, alternatively, would it be possible to have a `check_string(s)` function that performed a full-string match based on the same parameters?

As of right now, the invalid `| 25` gets swallowed.

Thanks for any information!

**Comment by AlexandreDecan** [comment]
Hello,

Thanks for reporting this bug! Indeed, the function should raise an error in that case. I'll have a look at why it doesn't and try to fix it.

**Comment by AlexandreDecan** [comment]
I found what went wrong, and I added some checks that raise a `ValueError` if the interval cannot be parsed correctly. 
This will be part of next patch release. Since I was working on using `poetry` instead of `setuptools` to manage `portion`, I'll release both changes at the same time. Expect some delay (a few days at most) depending on how successful I was to integrate `poetry` :-)

**Comment by Qix-** [comment]
Sounds good, thanks for the quick response!

**Comment by AlexandreDecan** [comment]
You're welcome ;)

I'll update this issue as soon as the fix is available on PyPI.

**Comment by AlexandreDecan** [comment]
Release 2.1.6 will be available on PyPI in a few minutes.

**Comment by Qix-** [comment]
Thanks! That's awesome, I appreciate it :)
