### ISSUE TITLE
Convert discrete intervals between closed and open forms

### ISSUE THREAD

**Issue by smcc-rai** [AlexandreDecan/portion#69]
Hi, I'm finding this library very convenient. Thank you for sharing it.

I noted that in answering #24 you discussed "extend" (convert to open) and "reduce" (convert to closed) operations on discrete intervals. I think it would be nice to include those operations in the library as utility functions.

I have a few use cases in mind:

1. Normalizing to either closed or open form before passing the interval's endpoints into an external query (e.g. SQL/pandas/etc.)
2. To convert to left-closed/right-open form, which is conventional for python/numpy sequence slicing.

**Comment by AlexandreDecan** [comment]
Hi, 

I understand the use-cases and the interest of having access to these functions. However, I don't think to integrate them in the library, because it's quite "specific". On the other hand, I think it could be interesting to have, in the documentation or within an "unofficial" module, a list of "recipes" that could be useful as a complement to portion.
