### ISSUE TITLE
Add capability for combine() to merge an arbitrary number of IntervalDicts

### ISSUE THREAD

**Issue by marcsarrel** [AlexandreDecan/portion#95]
It would be convenient if the `combine()` method could work with more than two `IntervalDict` objects at a time.  I know that I can chain `combine()` methods together to get the same result.  But, that means that I have to write more than one `how` function.  It would be conceptually simpler, easier to read and less error prone to have a single `how` function that accepts more than two arguments, and only call `combine()` once.

**Comment by AlexandreDecan** [comment]
Hello, 

I agree this would be convenient, but if we do that for `.combine`, we should do that for all other operations (including those on interval instances) for consistency. That said, and it relates to #33 and #62, the idiomatic way for doing so is to rely on `reduce`.

**Comment by marcsarrel** [comment]
Hi,

Thank you for the reply.  Unfortunately, `reduce` doesn't help in this case, unlike with other operations like `union` in #33.  The reason is that I have two different `how` functions.  Here are a few lines from my current code:

```
how_A = lambda x, y: something...
how_B = lambda x, y: something else...

result = int_dict_X.combine(int_dict_Y, how=how_A).combine(int_dict_Z, how=how_B)
```

**Comment by AlexandreDecan** [comment]
Oh I think I misunderstood the first comment. I see indeed some benefits in having this, but how to deal with keys that are missing in some dict?

**Comment by AlexandreDecan** [comment]
So, correct me if I'm wrong: my understanding of the initial comment is that you would like to have a `.combine` function accepting multiple `IntervalDict` instances and a *single* `how` function. This `how` function accepts as many parameters as the number of `IntervalDict` instances provided, plus the one on which the method is called. Right? 

If my understanding is correct, then the question I had in my previous comment holds: what do we do for keys that are not in some intervals? We have several options: 
(1) Only keys (i.e., overlapping intervals) are considered. This is different from the `combine` method we currently have, since it also takes into account non-overlapping intervals (their values are kept as-is); 
(2) We extend the current behaviour of `combine` by only considering keys that are in the "left-most" dict (i.e., the one on which `combine` is applied). But I don't see why we should do that; 
(3) We call the `how` functions with a variable number of arguments, depending on how many `IntervalDict` instances have an overlap on the keys (but this behaviour does not align with the existing `combine` method);
(4) We call the `how` functions with a fixed number of arguments, providing a special value (`None`? But `None` is not so special) for `IntervalDict` instances that do no overlap the current key (again, this is different from what we currently have for `combine` with 2 dicts); 
(5) We define a new function, parallel to `combine`, that only supports an "inner" join on multiple `IntervalDict`.

The other question I've in mind is whether we can write `combine` for multiple instances faster than chaining them. If we can, then definitely I think something should be added to portion to support this use-case. If we can't, then I see little value in adding this to portion, except the syntactic sugar it may provide (and I'm not strongly against this).

**Comment by marcsarrel** [comment]
> So, correct me if I'm wrong: my understanding of the initial comment is that you would like to have a `.combine` function accepting multiple `IntervalDict` instances and a single `how` function. This `how` function accepts as many parameters as the number of `IntervalDict` instances provided, plus the one on which the method is called. Right?

Yes, that is correct.

> (1) Only keys (i.e., overlapping intervals) are considered. This is different from the `combine` method we currently have, since it also takes into account non-overlapping intervals (their values are kept as-is);

This is less desirable.  It's roughly equivalent to doing an inner join.

>(2) We extend the current behaviour of `combine` by only considering keys that are in the "left-most" dict (i.e., the one on which `combine` is applied). But I don't see why we should do that;

Agree -- not so desirable.

>(3) We call the `how` functions with a variable number of arguments, depending on how many `IntervalDict` instances have an overlap on the keys (but this behaviour does not align with the existing `combine` method);

Agree -- not so desirable.

>(4) We call the `how` functions with a fixed number of arguments, providing a special value (`None`? But `None` is not so special) for `IntervalDict` instances that do no overlap the current key (again, this is different from what we currently have for `combine` with 2 dicts);

This is the most appealing, but I agree that None is not so special.  Large risk that someone uses None as a value in their interval dict.

**An alternative might be to pass _two_ values to `how` for each interval `IntervalDict`.  The first value would be the value from the `IntervalDict` for the current segment of the domain.  The second value would be a `bool` flag to indicate if the key is defined for the current segment of the domain.  Suggest using a `@dataclass(kw_only=True)` to pair the value and the flag.  This `@dataclass` would help with static type checking when users write their `how` functions**

>(5) We define a new function, parallel to `combine`, that only supports an "inner" join on multiple `IntervalDict`.

I think this is the same as (1), and not desirable.

**Comment by marcsarrel** [comment]
Another option would be to make a `@dataclass(kw_only=True)` with a single property named `value`.  That is, omit the `valid` flag property.  If there is no value defined in the current segment of the domain, leave the `value` property undefined.  The user can then test for the presence of the `value` property and decide what to do.

**Comment by marcsarrel** [comment]
Ok, I understand.  Please let me know what you decide.

However, even with my current solution of chaining two `combine` methods together as shown [above](https://github.com/AlexandreDecan/portion/issues/95#issuecomment-2347135086), I do not have full control of the `result` `IntervalDict`.

For those portions of the merged domain where not all of the input `IntervalDicts` are defined, I must accept what the `combine` method returns because it won't call my `how` function.  I can have some control by re-ordering the `IntervalDict`s in the chain of `combine` methods.  But, I doubt that would be a general solution.

Maybe you could also provide a generic wrapper function that users could call.

**Comment by marcsarrel** [comment]
For option (4) above, maybe you could steal this idea to create an `undefined` value in the Portion library.

https://pypi.org/project/undefined

**Comment by AlexandreDecan** [comment]
Thanks, that's what I had in mind yesterday. Basically, either we put in the doctstring that `missing_value` (name to be defined) can be passed to set the value that will be provided to `how` if a key is missing (we can use `**kwargs` to detect whether it is set or not, so it won't clash with `None`), or we can use a sentinel value for this sole purpose (as is made above in `undefined`). 

That said, I still need to think how to combine multiple dicts efficiently at once. That won't be easy. In the meantime, what I can do is to add this `missing_value` parameter to `combine` so that `how` will be called even when some keys are missing (hence it will be easier for you to chain `combine`).

I'll see if I can find some time to work on this. This shouldn't be hard to implement, since we mostly need to iterate on all key/value of the left dict and right dict separately and call the how function appropriately.

**Comment by AlexandreDecan** [comment]
Could you please have a look at #96 ? It doesn't solve the current issue, but is an interesting, I think, step towards making it easier to chain calls to `.combine` to gather values from multiple `IntervalDict`. I think that, based on this change, one would be able to create a recipe for a `.combine` method accepting more than 2 dicts and a `how` function accepting `n` parameters. First step would be to collect all values from all dicts using appropriate `how` functions in chained calls to `combine`, then second step would be to apply/map the n-ary `how` function on the resulting `IntervalDict`. This won't be efficient, but it can be very convenient.

**Comment by AlexandreDecan** [comment]
What I have in mind: 

 - Let's start with an empty list of parameters for an IntervalDict: `init = IntervalDict([P.open(-P.inf, P.inf), [])])`;
 - Assume we have `d1, ..., dn` instances of `IntervalDict` that we want to combine using a function `f` taking `n` parameters; 
 - Then we can define `gather = lambda x, y: x.append(y)`; 
 - Then I guess `init.combine(d1, how=gather, missing=None).combine(d2, how=gather, missing=None)....` should produce an `IntervalDict` of lists of parameter values/None. Let's call it `gathered`; 
 - Then we can transform `gathered` by calling `f` for each value, something like this: `[i, f(*v) for i, v in gathered.items()]` and pass this expression to the constructor of `IntervalDict`. 

Could you give it a try and tell me if this approach works and solves your issue? If so, I can probably integrate it directly to the `.combine` method, definitely fixing this issue :-)

**Comment by AlexandreDecan** [comment]
Hello, 

The following recipe can be used to combine multiple IntervalDict instances. The `how` function is called with a variable number of parameters. The main steps are: 
1. Create an IntervalDict to initialize the whole domain with a tuple; 
2. Use an accumulator function to add items to tuples, one by one; 
3. Chain `.combine` calls to accumulate parameters from input IntervalDict; 
4. Do a kind of "map" on the resulting IntervalDict to call the `how` function on these parameters;
5. During this map, exclude empty tuples (they correspond to ranges on the domain where there is no value in the given IntervalDict instances).

```python
def combine_all(dicts, how):
    d = P.IntervalDict([(P.open(-P.inf, P.inf), tuple())])
    acc = lambda t, v: (*t, v)

    for o in dicts:
        d = d.combine(o, acc)

    r = []
    for i, v in d.items():
        if len(v) > 0:
            r.append((i, how(*v)))

    return P.IntervalDict(r)
```

Applied on the following dicts, as an example: 

```python
d1 = P.IntervalDict([(P.closed(1, 3) | P.closed(5, 7), 1)])
d2 = P.IntervalDict([(P.closed(2, 4) | P.closed(6, 8), 2)])
d3 = P.IntervalDict([(P.closed(3, 5), 4)])

print(combine_all([d1, d2, d3], lambda *x: sum(x)))
```

... outputs `{[1,2) | (5,6): 1, [2,3) | [6,7]: 3, [3]: 7, (3,4]: 6, (4,5): 4, [5]: 5, (7,8]: 2}`.

It is quite easy to transform this to an "inner join" (instead of an "outer" one) by changing `if len(v) > 0:` to `if len(v) == len(dicts)`. It is also quite easy to integrate the new `missing` parameter of `combine`, (1) by adding it to the calls to `combine` obviously and (2) by changing `if len(v) > 0` to check that any one item in the tuple is not `missing` (i.e., if all entries are `missing`, drop it). 

I'll add a reference to this snippet in the documentation, but I do not plan to integrate it as part of the API since it is really inefficient and a bit of a "hack" :-)

**Comment by marcsarrel** [comment]
Thank you.  I will give it a try...

**Comment by AlexandreDecan** [comment]
Keep me informed so I can release v2.1.5 or make changes before it's release.

**Comment by marcsarrel** [comment]
I thought you weren't going to release `combine_all()` as part of Portion?

**Comment by AlexandreDecan** [comment]
I won't, but the "missing" parameter for "combine" deserves a release. It is very convenient for this recipe when intervals do not share a same domain.
